language: ruby
rvm:
  - 2.0.0

env:
  - DB=postgresql

script:
  - bundle exec rake db:reset RAILS_ENV=test
  - bundle exec rspec

before_script:
  - cp config/database.ci.yml config/database.yml
  - cp config/initializers/secret_token.ci.rb config/initializers/secret_token.rb
  - bundle exec rake db:create RAILS_ENV=test