language: ruby
rvm:
  - 2.0.0

env:
  - DB=postgresql

script:
  - bundle exec rake db:reset RAILS_ENV=test
  - bundle exec rspec

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create RAILS_ENV=test