defaults: &defaults
   dummy: ""

development:
  <<: *defaults
  paperclip:
    project:
      map:
        image:
          storage_path: "dev/uploads/projects/:project_id/maps/:map_id/images/:name-:style-:id.:extension"
        archive:
          storage_path: "dev/uploads/projects/:project_id/maps/:map_id/archives/:name-:id.:extension"


production:
  <<: *defaults
  paperclip:
    project:
      map:
        image:
          storage_path: "uploads/projects/:project_id/maps/:map_id/images/:name-:style-:id.:extension"
        archive:
          storage_path: "uploads/projects/:project_id/maps/:map_id/archives/:name-:id.:extension"

test:
  <<: *defaults
  paperclip:
    project:
      map:
        image:
          storage_path: "public/uploads/test/projects/:project_id/maps/:map_id/images/:name-:style-:id.:extension"
        archive:
          storage_path: "public/uploads/test/projects/:project_id/maps/:map_id/archives/:name-:id.:extension"

