theme: advanced
width: 614px
theme_advanced_buttons1:
  - bold
  - italic
  - undersocre
  - link
  - unlink
  - bullist
  - numlist
  - forecolor
  - backcolor
  - code
theme_advanced_buttons2: ""
theme_advanced_buttons3: ""
